export { Slide1 as ScreenSlide1 } from './slide1'
export { Slide2 as ScreenSlide2 } from './slide2'
export { Slide3 as ScreenSlide3 } from './slide3'
export { Login as ScreenLogin } from './login'
export { Register as ScreenRegister } from './register'